name: Build

# on:
#   pull_request:
#     branches:
#       - main
#     paths:
#       - 'kong/**/*.lua'
#       - 'spec/*.lua'

on: push

jobs:
  linting:
    name: Linting code.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v0
        with:
          args: kong
  unit-tests:
    name: Running unit tests.
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kong_version:
        - "2.7.x"
        - "2.8.x"
        - "nightly"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: Kong/kong-pongo-action@v1
        with:
          kong_version: ${{ matrix.kong_version }}
      - run: pongo run