name: Build

on:
  pull_request:
    branches:
      - main
jobs:
  linting:
    name: Linting code.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v0
        with:
          args: kong spec
  unit-tests:
    needs: linting 
    name: Running unit tests.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: Kong/kong-pongo-action@v1
        with:
          kong_version: "2.8.x"
      - run: pongo run