name: CI

on: [push]

jobs:
  linting:
    name: Linting code.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v0
        with:
          args: kong